ARG SICKCHILL_VERSION='2022.02.20'

FROM centos:7 AS su-exec-builder

RUN set -x && \
    yum update -y && \
    yum install -y \
      gcc \
      make \
      git \
    && \
    git clone --depth 1 https://github.com/ncopa/su-exec.git /opt/su-exec && \
    cd /opt/su-exec && \
    make

FROM centos:7
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG SICKCHILL_VERSION

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='sickchill' \
    APPUID='10000' \
    APPGID='10000' \
    SICKCHILL_VERSION="${SICKCHILL_VERSION}"

# Copy config files
COPY --from=su-exec-builder /opt/su-exec/su-exec /usr/local/bin/su-exec
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    ConfigureUser && \
    yum install -y epel-release && \
    yum update -y && \
    yum install -y \
      git \
      gcc \
      gcc-c++ \
      python3-devel \
      python3-pip \
      openssl-devel \
      make \
      curl \
      cargo \
    && \
    pip3 --no-cache-dir install --upgrade \
      pip \
      setuptools \
      virtualenv \
      wheel \
    && \
    mkdir /opt/sickchill && \
    virtualenv /opt/sickchill && \
    . /opt/sickchill/bin/activate && \
    pip3 --no-cache-dir install --upgrade \
      git+https://github.com/SickChill/SickChill.git@${SICKCHILL_VERSION} \
    && \
    yum history -y undo last && \
    yum install -y \
     bash \
     ca-certificates \
     curl \
     jq \
     libffi \
     libxml2-python \
     mediainfo \
     nodejs \
     python3 \
     python3-lxml \
     python3-pip \
     unrar \
    && \
    mkdir -p /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    yum clean all && \
    rm -rf /opt/sickchill/.git* \
           /tmp/* \
           /var/cache/yum/* \
           /var/tmp/* \
           ${HOME}/.cache \
           ${HOME}/.local \
           ${HOME}/.cargo
### Volume
VOLUME ["/config", "/downloads", "/tv", "/animes"]

### Expose ports
EXPOSE 8081

### Running User: not used, managed by docker-entrypoint.sh
#USER sickchill

### Start Sickrage
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["sickchill"]
