FROM centos:7
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG SICKCHILL_VERSION='2021.02.13-1'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='sickchill' \
    APPUID='10000' \
    APPGID='10000' \
    SICKCHILL_VERSION="${SICKCHILL_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    ConfigureUser && \
    yum-config-manager --add-repo /tmp/custom.repo && \
    yum install -y epel-release && \
    yum update -y && \
    yum install -y \
      git \
      gcc \
      gcc-c++ \
      python3-devel \
      python3-pip \
      openssl-devel \
      make \
      curl \
      cargo \
    && \
    pip3 --no-cache-dir install --upgrade setuptools pip && \
    pip3 --no-cache-dir install --upgrade pyopenssl && \
    curl -sL https://github.com/SickChill/SickChill/archive/v${SICKCHILL_VERSION}.tar.gz -o /tmp/sickchill.tar.gz && \
    cd /tmp && \
    tar xzf /tmp/sickchill.tar.gz && \
    mv /tmp/SickChill-${SICKCHILL_VERSION} /opt/sickchill && \
    yum history -y undo last && \
    yum install -y \
     ca-certificates \
     python3 \
     libxml2-python \
     python3-lxml \
     unrar \
     nodejs \
     su-exec \
     curl \
     jq \
    && \
    mkdir -p /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    yum clean all && \
    rm -rf /opt/sickchill/.git* \
           /tmp/* \
           /var/cache/yum/* \
           /var/tmp/* \
           ${HOME}/.cache \
	       ${HOME}/.cargo
### Volume
VOLUME ["/config", "/downloads", "/tv", "/animes"]

### Expose ports
EXPOSE 8081

### Running User: not used, managed by docker-entrypoint.sh
#USER sickchill

### Start Sickrage
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["sickchill"]
