FROM alpine:3.19.1
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG SICKCHILL_VERSION='2024.2.27'
ARG UNRAR_VERSION='6.1.3'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm'  \
    APPUSER='sickchill' \
    APPUID='10000' \
    APPGID='10000' \
    SICKCHILL_VERSION="${SICKCHILL_VERSION}"\
    UNRAR_VERSION="${UNRAR_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    ConfigureUser && \
    apk --no-cache upgrade && \
    apk add --no-cache --virtual=build-deps \
      curl \
      make \
      gcc \
      g++ \
      git \
      python3-dev \
      py3-pip \
      openssl-dev \
      cargo \
      libffi-dev \
      libxml2-dev\
      libxslt-dev\
    && \
    apk add --no-cache --virtual=run-deps \
      bash \
      curl \
      ca-certificates \
      python3 \
      py3-pip \
      jq \
      libffi \
      libxml2 \
      libxslt \
      openssl \
      nodejs \
      su-exec \
      mediainfo \
      tzdata \
    && \
    pip3 --no-cache-dir install --upgrade \
      pip \
      setuptools \ 
      virtualenv \
      wheel \
    && \
    mkdir /opt/sickchill && \
    virtualenv /opt/sickchill && \
    . /opt/sickchill/bin/activate && \
    pip3 --no-cache-dir install --upgrade \
      git+https://github.com/SickChill/SickChill.git@${SICKCHILL_VERSION} \ 
    && \
    curl -SsL https://www.rarlab.com/rar/unrarsrc-${UNRAR_VERSION}.tar.gz -o /tmp/unrar.tar.gz && \ 
    cd /tmp && \
    tar xzf /tmp/unrar.tar.gz && \
    cd unrar && \
    make -f makefile && \
    install -v -m755 unrar /usr/bin && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    mkdir -p /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /opt/sickchill/.git* \
           /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/* \
           ${HOME}/.cache \
           ${HOME}/.local \
	   ${HOME}/.cargo

### Volume
VOLUME ["/config", "/downloads", "/tv", "/animes"]

### Expose ports
EXPOSE 8081

### Running User: not used, managed by docker-entrypoint.sh
#USER sickchill

### Start Sickrage
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["sickchill"]
