FROM alpine:3.14
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG SICKCHILL_VERSION='2021.07.12-4'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm'  \
    APPUSER='sickchill' \
    APPUID='10000' \
    APPGID='10000' \
    SICKCHILL_VERSION="${SICKCHILL_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    ConfigureUser && \
    apk --no-cache upgrade && \
    apk add --no-cache --virtual=build-deps \
      curl \
      make \
      gcc \
      g++ \
      python3-dev \
      py3-pip \
      openssl-dev \
      cargo \
      libffi-dev \
      libxml2-dev\
      libxslt-dev\
    && \
    apk add --no-cache --virtual=run-deps \
      bash \
      curl \
      ca-certificates \
      python3 \
      jq \
      libxml2 \
      libxslt \
      openssl \
      nodejs \
      unrar  \
      su-exec \
      mediainfo \
      tzdata \
    && \
    pip3 --no-cache-dir install --upgrade setuptools && \
    pip3 --no-cache-dir install --upgrade pyopenssl && \
    curl -sL https://github.com/SickChill/SickChill/archive/v${SICKCHILL_VERSION}.tar.gz -o /tmp/sickchill.tar.gz && \
    cd /tmp && \
    tar xzf /tmp/sickchill.tar.gz && \
    mv /tmp/SickChill-${SICKCHILL_VERSION} /opt/sickchill && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    mkdir -p /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /opt/sickchill/.git* \
           /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/* \
           ${HOME}/.cache \
	       ${HOME}/.cargo

### Volume
VOLUME ["/config", "/downloads", "/tv", "/animes"]

### Expose ports
EXPOSE 8081

### Running User: not used, managed by docker-entrypoint.sh
#USER sickchill

### Start Sickrage
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["sickchill"]
